#include "geekcode.h"

const struct stuff gc_type[] = {
	{1, "GB",	"Geek of Business"},
	{2, "GC",	"Geek of Classics"},
	{3, "GCA",	"Geek of Commercial Arts"},
	{4, "GCM",	"Geek of Computer Management"},
	{5, "GCS",	"Geek of Computer Science"},
	{6, "GCC",	"Geek of Communications"},
	{7, "GE",	"Geek of Engineering"},
	{8, "GED",	"Geek of Education"},
	{9, "GFA",	"Geek of Fine Arts"},
	{10, "GG",	"Geek of Government"},
	{11, "GH",	"Geek of Humanities"},
	{12, "GIT",	"Geek of Information Technology"},
	{13, "GJ",	"Geek of Jurisprudence (Law)"},
	{14, "GLS",	"Geek of Library Science"},
	{15, "GL",	"Geek of Literature"},
	{16, "GMC",	"Geek of Mass Communications"},
	{17, "GM",	"Geek of Math"},
	{18, "GMD",	"Geek of Medicine"},
	{19, "GMU",	"Geek of Music"},
	{20, "GPA",	"Geek of Performing Arts"},
	{21, "GP",	"Geek of Philosophy"},
	{22, "GS",	"Geek of Science"},
	{23, "GSS",	"Geek of Social Science"},
	{24, "GTW",	"Geek of Technicial Writing"},
	{25, "GO",	"Geek of Other"},
	{26, "GU",	"Geek of Undecided"},
	{27, "G!",	"Geek of No Qualifications"},
	{28, "GAT",	"Geek of All Trades"},
	SENTINEL
};
